=== JavierCarrillodev/Lenguajes-de-Marcas/XML_XSD/ejercluster.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cluster">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nodo" minOccurs="0" maxOccurs="2">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="maquina" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="nombre" type="xs:string"/>

                                        <xs:element name="sistema_operativo" type="xs:string"/>

                                        <xs:element name="red">
                                            <xs:complexType>
                                                <xs:sequence>

                                                    <xs:element name="ip" type="xs:string"/>

                                                    <xs:element name="mac" type="xs:string"/>

                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                        <xs:attribute name="ip" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/XML_XSD/cluster.xml
<?xml version="1.0" encoding="UTF-8"?>

<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ejercluster.xsd">
    <nodo nombre="Modric" ip="123.43.5.2">
        <maquina>
            <nombre>Hacker</nombre>
            <sistema_operativo>Ubuntu</sistema_operativo>
            <red>
                <ip>123.423.2.4</ip>
                <mac>2FH467bj3</mac>
            </red>
        </maquina>
        <maquina>
            <nombre>Pepe</nombre>
            <sistema_operativo>Windows</sistema_operativo>
            <red>
                <ip>121.43.6.4</ip>
                <mac>2F423F67bj3</mac>
            </red>
        </maquina>
    </nodo>
    <nodo nombre="Jose" ip="173.45.7.1">
        <maquina>
            <nombre>Hacker</nombre>
            <sistema_operativo>Linux</sistema_operativo>
            <red>
                <ip>123.423.2.4</ip>
                <mac>2FH467bj3</mac>
            </red>
        </maquina>
        <maquina>
            <nombre>Antonio</nombre>
            <sistema_operativo>Windows</sistema_operativo>
            <red>
                <ip>123.53.6.4</ip>
                <mac>2F423F67bj3</mac>
            </red>
        </maquina>
    </nodo>
</cluster>
