=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/ejerpelis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="peliculas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:attribute name="id" type="xs:string" use="required"/>

                            <xs:element name="titulo" type="xs:string"/>

                            <xs:element name="anio" type="xs:gYear"/>

                            <xs:element name="genero" type="xs:string"/>

                            <xs:element name="actores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="actor" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/pelis.xml
<?xml version="1.0" encoding="UTF-8"?>
<peliculas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="ejerpelis.xsd">
    <pelicula id="001">
        <titulo>Matrix</titulo>
        <anio>1999</anio>
        <genero>Acción</genero>
        <actores>
            <actor>Keanu Reeves</actor>
            <actor>Laurence Fishburne</actor>
        </actores>
    </pelicula>
    <pelicula id="002">
        <titulo>Inception</titulo>
        <anio>2010</anio>
        <genero>Ciencia ficción</genero>
        <actores>
            <actor>Leonardo DiCaprio</actor>
            <actor>Joseph Gordon-Levitt</actor>
        </actores>
    </pelicula>
</peliculas>
