=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/ejer1es.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="estudiantes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estudiante" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="edad" type="xs:integer"/>
                            <xs:element name="carrera" type="xs:string">
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="matricula" type="xs:string" use="required"/>
                        <xs:attribute name="activo" type="xs:boolean" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/ejer1.xml
<?xml version="1.0" encoding="UTF-8"?>
<estudiantes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="ejer1es.xsd">
    <estudiante matricula="2023001" activo="true">
        <nombre>María López</nombre>
        <edad>20</edad>
        <carrera>Ingeniería</carrera>
    </estudiante>
    <estudiante matricula="2023002" activo="false">
        <nombre>Carlos Ruiz</nombre>
        <edad>22</edad>
        <carrera>Medicina</carrera>
    </estudiante>
</estudiantes>
