=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/ejerred.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="red_social">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="amigos" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="amigo" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="nombre" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/red.xml
<?xml version="1.0" encoding="UTF-8"?>
<red_social xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="ejerred.xsd">
    <usuario nombre="Juan">
        <amigos>
            <amigo nombre="Carlos"/>
            <amigo nombre="Ana"/>
        </amigos>
    </usuario>
    <usuario nombre="Ana">
        <amigos>
            <amigo nombre="Juan"/>
            <amigo nombre="Pedro"/>
        </amigos>
    </usuario>
</red_social>
