=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/ejermadrid.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="liga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="arbitros">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="arbitro" type="xs:string"  minOccurs="0" maxOccurs="3"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="equipos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="entrenador" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="presidente" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="jugadores">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="jugador" type="xs:string" minOccurs="14" maxOccurs="24"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nombre" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/madrid.xml
<liga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="laliga" xsi:noNamespaceSchemaLocation="ejermadrid.xsd">
    <arbitros>
        <arbitro>Melissa</arbitro>
        <arbitro>Aaron</arbitro>
        <arbitro>Salva</arbitro>
    </arbitros>
    <equipos>
        <equipo nombre="Real Madrid">
            <entrenador>Ancelotti</entrenador>
            <presidente>Tito Floren</presidente>
            <jugadores>
                <jugador>Bellingham</jugador>
                <jugador>Luka Modric</jugador>
                <jugador>Vallejo</jugador>
            </jugadores>
        </equipo>
        <equipo> </equipo>
    </equipos>
</liga>
