=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/ejerbiblio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="autor">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string">
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nacionalidad" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="genero" type="xs:string">
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="isbn" type="xs:string" use="required"/>
                        <xs:attribute name="aÃ±o" type="xs:gYear" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/biblio.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="ejerbiblio.xsd">
    <libro isbn="978-3-16-148410-0" año="2005">
        <titulo>El señor de los anillos</titulo>
        <autor nacionalidad="británica">
            <nombre>J.R.R. Tolkien</nombre>
        </autor>
        <genero>Fantasía</genero>
    </libro>
    <libro isbn="978-84-376-0494-7" año="1999">
        <titulo>La sombra del viento</titulo>
        <autor nacionalidad="española">
            <nombre>Carlos Ruiz Zafón</nombre>
        </autor>
        <genero>Misterio</genero>
    </libro>
</biblioteca>
