=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/ejerfactura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="direccion" type="xs:string">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="productos"  minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                          <xs:element name="producto" maxOccurs="unbounded">
                              <xs:complexType>
                                  <xs:attribute name="codigo" type="xs:string" use="required"/>
                                  <xs:attribute name="cantidad" type="xs:string" use="required"/>
                                  <xs:attribute name="precio" type="xs:decimal" use="required"/>                                          </xs:complexType>
                          </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="total" type="xs:string">
                </xs:element>
            </xs:sequence>
            <xs:attribute name="numero" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/Recuperacion xsd/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura numero="F001" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ejerfactura.xsd">
    <cliente>
        <nombre>Pedro LÃ³pez</nombre>
        <direccion>Calle Falsa 123</direccion>
    </cliente>
    <productos>
        <producto codigo="P100" cantidad="2" precio="50.00"/>
        <producto codigo="P200" cantidad="1" precio="30.00"/>
    </productos>
    <total>130.00</total>
</factura>
