=== JavierCarrillodev/Lenguajes-de-Marcas/Por si repaso xml/ejerreceta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="libro_de_cocina">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="receta" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredientes" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingrediente" type="xs:string">
                                        </xs:element>
                                        <xs:element name="pasos" minOccurs="0" maxOccurs="2">
                                            <xs:complexType>
                                                <xs:sequence>

                                                    <xs:element name="medidad" type="xs:string"/>

                                                    <xs:element name="tamano" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/Por si repaso xml/receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<libro_de_cocina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="ejerreceta.xsd">
    <receta numero="1">
        <ingredientes>
            <ingrediente>Arroz</ingrediente>
            <ingrediente>Tomillo</ingrediente>
            <ingrediente>Pimienta</ingrediente>
        </ingredientes>
        <pasos>
            <medida> 5 gramos de tomillo</medida>
            <tamano>Grande</tamano>
        </pasos>
    </receta>
    <receta numero="2">
        <ingredientes>
            <ingrediente>Arroz</ingrediente>
            <ingrediente>Tomillo</ingrediente>
            <ingrediente>Pimienta</ingrediente>
        </ingredientes>
        <pasos>
            <paso numero="1"> Calentar agua hasta hervir</paso>
            <paso numero="2"> Echar tomillo y arroz</paso>
        </pasos>
    </receta>
</libro_de_cocina>
