=== JavierCarrillodev/Lenguajes-de-Marcas/Por si repaso xml/ejertorneo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Torneo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fecha_ini" type="xs:date"/>

                <xs:element name="fecha_fin" type="xs:date"/>

                <xs:element name="partidos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="partido" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fecha" type="xs:date"/>
                                        <xs:element name="jugadores">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="jugador" minOccurs="0" maxOccurs="2">
                                                        <xs:complexType>
                                                            <xs:sequence>

                                                                <xs:element name="nombre" type="xs:string"/>

                                                                <xs:element name="edad" type="xs:int">

                                                                </xs:element>
                                                                <xs:element name="resultados">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="set" minOccurs="0" maxOccurs="unbounded">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>

                                                                                        <xs:element name="resultado" type="xs:int">

                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="numero" type="xs:int" use="required"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="numero" type="xs:int" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="numero" type="xs:int" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JavierCarrillodev/Lenguajes-de-Marcas/Por si repaso xml/torneo.xml
<?xml version="1.0" encoding="UTF-8"?>


<Torneo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="ejertorneo.xsd">
    <fecha_ini>12/02/2004</fecha_ini>
    <fecha_fin>25/02/2004</fecha_fin>
    <partidos>
        <partido>
            <fecha>12/02/2004</fecha>
            <jugadores>
                <jugador numero="1">
                    <nombre>Javi</nombre>
                    <edad>20</edad>
                </jugador>
                <jugador numero="2">
                    <nombre>Victoria</nombre>
                    <edad>19</edad>
                </jugador>
            </jugadores>
            <resultados>
                <set numero="1">
                    <resultado>6-3</resultado>
                </set>
                <set numero="2">
                    <resultado>6-4</resultado>
                </set>
                <set numero="3">
                    <resultado>6-3</resultado>
                </set>
            </resultados>
        </partido>


        <partido>
            <fecha>14/02/2004</fecha>
            <jugadores>
                <jugador numero="1">
                    <nombre>Alex</nombre>
                    <edad>24</edad>
                </jugador>
                <jugador numero="2">
                    <nombre>Pepe</nombre>
                    <edad>20</edad>
                </jugador>
            </jugadores>
            <resultados>
                <set numero="1">
                    <resultado>7-5</resultado>
                </set>
                <set numero="2">
                    <resultado>6-4</resultado>
                </set>
                <set numero="3">
                    <resultado>6-1</resultado>
                </set>
            </resultados>
        </partido>

        <partido>
            <fecha>15/02/2004</fecha>
            <jugadores>
                <jugador numero="1">
                    <nombre>Jose</nombre>
                    <edad>18</edad>
                </jugador>
                <jugador numero="2">
                    <nombre>Antonio</nombre>
                    <edad>34</edad>
                </jugador>
            </jugadores>
            <resultados>
                <set numero="1">
                    <resultado>6-1</resultado>
                </set>
                <set numero="2">
                    <resultado>6-2</resultado>
                </set>
                <set numero="3">
                    <resultado>6-0</resultado>
                </set>
            </resultados>
        </partido>
    </partidos>
</Torneo>
